# Generated by Django 4.1.1 on 2022-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='static\\pictures')),
                ('disc', models.TextField()),
                ('button', models.CharField(max_length=10)),
            ],
        ),
    ]
