# Generated by Django 4.1.1 on 2022-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservices',
            name='img',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
