# Generated by Django 4.1.1 on 2022-10-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeservice_test_delete_homeservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
