# Generated by Django 4.1.1 on 2022-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservice',
            name='header',
            field=models.CharField(max_length=10),
        ),
    ]
