# Generated by Django 4.1.1 on 2022-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homeservice_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=20)),
                ('Picture', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=20)),
                ('Picture', models.ImageField(upload_to='pictures')),
                ('Discription', models.TextField()),
                ('Buutton', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeService',
        ),
    ]
