# Generated by Django 4.1.1 on 2022-10-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_introduction_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='Picture',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
